### ISSUE TITLE
Analysis of unpolarized data

### ISSUE THREAD

**Issue by sergiopalmavera** [alachins/raisd#10]
Hello!
I tested RAiSD on unpolarized data and he program ran smoothly. 

However, the mu-statistic is calculated based on the counts for the derived allele. 

I would imagine that for cases of unpolarized data the minor allele is counted instead (i.e. folded SFS). 

I went through the paper, but I couldn't find such information, could you please help me clarify this issue?

Thanks!

**Comment by alachins** [comment]
Hello Sergio,

The derived-allele count is used for the mu-sfs factor of the mu statistic.
In fact, for this purpose, we calculate the number of singletons and SNPs with N-1 derived alleles (N is the sample size) per evaluated window. We assign equal weights to both.

Best regards,
Nikos

**Comment by sergiopalmavera** [comment]
Hello Nikos,

does this mean that the software only works on data for which the ancestral and derived allele is known?

Best regards
Sergio

**Comment by alachins** [comment]
Hello Sergio,
I think its the opposite. You do not need to know which is the ancestral and which is the derived allele. RAiSD uses SNP-vector patterns in all computations, and the criterion for finding patterns is to have perfect LD under the infinite-sites model. I hope this helps.
Best regards,
Nikos
