### ISSUE TITLE
Input vcf file

### ISSUE THREAD

**Issue by palomo11** [alachins/raisd#13]
Hi,

I would like to detect selective sweeps in a set of bacterial genomes, and RAiSD seems as a perfect tool for it. But I have a question about the input vcf file I should use to run RAiSD.

The bacterial genomes (or more precisely metagenome-assembled genomes) were recovered from 12 drinking water treatment plants (2 samples per plant). Therefore, I have 24 bam files. To get the vcf I was thinking to use freebayes (any other recommendation?). The question is if I have to get 1 vcf per bam file, or I should run freebayes in multi bam mode to get only 1 vcf (for each genome).

**Comment by alachins** [comment]
Hi there,
You need to create only 1 vcf file containing all the samples you want to include in the analysis with RAiSD.
Nikos A.

**Comment by palomo11** [comment]
OK. Thanks. I will do that, then.
