### ISSUE TITLE
Duplicate windows variable statistic values

### ISSUE THREAD

**Issue by silastittes** [alachins/raisd#17]
Hello, 
Thanks for your work! I noticed that some windows are repeated in my analysis. Here's an example:

```
272909792       272908832       272910752       1.210e-01       1.032e+00       2.156e+00       2.693e-01
272909792       272908832       272910752       1.210e-01       1.032e+00       2.197e+00       2.744e-01
272909792       272908832       272910752       1.210e-01       1.032e+00       2.197e+00       2.744e-01
272909792       272908832       272910752       1.210e-01       1.032e+00       2.243e+00       2.801e-01
272909792       272908832       272910752       1.210e-01       1.032e+00       2.232e+00       2.787e-01
272909792       272908832       272910752       1.210e-01       1.032e+00       1.898e+00       2.370e-01
272909792       272908832       272910752       1.210e-01       1.032e+00       1.948e+00       2.432e-01
```
Is this behavior expected? 
Thank you!

**Comment by alachins** [comment]
Can you check whether there are multiple SNPs at the same position in your dataset?
I can look into that if you sent me a small sample of your file that reproduces this behavior.

**Comment by silastittes** [comment]
Here's the input and output files needed to reproduce the behavior. 

Thanks for looking in to this!

command:
`raisd-master/RAiSD -R -s -m 0.05 -n LR_dup2 -I SNPs_only.recode.vcf -S LR_Crucero_Lagunitas_IDkey.txt -f`


(note, I've appended .txt so GitHub would upload). 
[RAiSD_Info.LR_dup2.txt](https://github.com/alachins/raisd/files/4141292/RAiSD_Info.LR_dup2.txt)
[RAiSD_Report.LR_dup2.1.txt](https://github.com/alachins/raisd/files/4141293/RAiSD_Report.LR_dup2.1.txt)
[SNPs_only.recode.vcf.txt](https://github.com/alachins/raisd/files/4141294/SNPs_only.recode.vcf.txt)
[LR_Crucero_Lagunitas_IDkey.txt](https://github.com/alachins/raisd/files/4141295/LR_Crucero_Lagunitas_IDkey.txt)

**Comment by alachins** [comment]
I just pushed version 2.5 that fixes this. There was a bug (due to typecasting) that was causing some site positions to be off by 1 bp when stored in memory.  Can you please try v2.5 on your full dataset and let me know?

Thank you very much for reporting this.

**Comment by silastittes** [comment]
I'm not seeing any duplicate windows with the update! I've closed the issue. Thank you!
