### ISSUE TITLE
ERROR: unexpected error during parser initialization

### ISSUE THREAD

**Issue by foala** [alachins/raisd#20]
Hi,
I am new to raisd.
I am using vcf filed generated by freebayes of a population of 50 (35 scaffolds) as an input.
I get this error when I start running

ERROR: unexpected error during parser initialization

 the command used is 
 Command: ./RAiSD -n v2 -I ./input -f

please assist

**Comment by alachins** [comment]
This error appears when the file format is not recognized. 
Can you please send me the input file to look into that?

**Comment by foala** [comment]
Hi, 
Thank your for your prompt reply.
It is a huge vcf file (25Gb).

**Comment by foala** [comment]
can you share with me a sample VCf file that works? to make sure its a format issue

**Comment by alachins** [comment]
Can you extract the first 50-100 lines? Which version are you using? 
The very first check for VCF files is that the file starts with the string: "##fileformat=VCF"
Can you check this?

**Comment by foala** [comment]
Thank you for your reply
here is the header from my VCF

`##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##fileDate=20200606
##source=freeBayes v1.3.2-dirty
##reference=ref.fa
##contig=<ID=1,length=126869364>
##contig=<ID=2,length=122154150>
##contig=<ID=3,length=121014193>
##contig=<ID=4,length=112437421>
##contig=<ID=5,length=91981419>
##contig=<ID=6,length=91094987>
##contig=<ID=scaffold_7|arrow,length=84945525>
##contig=<ID=8,length=72902898>
##contig=<ID=9,length=65417778>
##contig=<ID=10,length=39825854>
##contig=<ID=11,length=38161587>
##contig=<ID=12,length=35666266>
##contig=<ID=13,length=33883921>
##contig=<ID=14,length=29721013>
##contig=<ID=15,length=24097470>
##contig=<ID=16,length=23310080>
##contig=<ID=17,length=14193008>
##contig=<ID=18,length=11635456>
##contig=<ID=scaffold_19|arrow,length=8193377>
##contig=<ID=20,length=8171170>
##contig=<ID=21,length=7847294>
##contig=<ID=22,length=6513200>
##contig=<ID=23,length=6217371>
##contig=<ID=24,length=2603342>
##contig=<ID=25,length=2231191>
##contig=<ID=26,length=2144202>
##contig=<ID=27,length=1398196>
##contig=<ID=28,length=1154547>
##contig=<ID=29,length=938903>
##contig=<ID=30,length=635314>
##contig=<ID=31,length=582163>
##contig=<ID=32,length=556105>
##contig=<ID=33,length=491258>
##contig=<ID=34,length=252256>
##contig=<ID=35,length=141896>
##phasing=none
##commandline="freebayes -L bam.txt -@ filtered20.vcf.gz -l --region=scaffold_1|arrow:1-126869364 -f ref.fa"
##filter="QUAL > 20"
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of samples with data">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total read depth at the locus">
##INFO=<ID=DPB,Number=1,Type=Float,Description="Total read depth per bp at the locus; bases in reads overlapping / bases in haplotype">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Total number of alternate alleles in called genotypes">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=AF,Number=A,Type=Float,Description="Estimated allele frequency in the range (0,1]">
##INFO=<ID=RO,Number=1,Type=Integer,Description="Count of full observations of the reference haplotype.">
`

**Comment by alachins** [comment]
I just put these lines in a txt file and RAiSD v2.8 (the latest) identifies that it is a vcf header. So the parser is correctly initialized.

**Comment by foala** [comment]
I am using RAiSD v2.8 too. 
I did what you did (1000 lines of my VCF into a new vcf). I still get the same error.

**Comment by alachins** [comment]
That's very strange. I can check it in more detail if you can send me an input file, no matter how small, as long as it generates the error. n.alachiotis@gmail.com

**Comment by foala** [comment]
Thank you very much for your help. 
 I will keep you posted, and will close this thread for now
