### ISSUE TITLE
-X option does not work

### ISSUE THREAD

**Issue by ymatmt** [alachins/raisd#27]
Hi, 

I want to remove telomere regions in the genome so I run raisd using -X option with tab txt as follows,

RAiSD -n vcf_run -t -f -P -R -s -A 0.995 -X remove.txt -I ${VFILE}

cat remove.txt
A1	0	100000
A1	243404654	243504654
X	0	100000
X	129529249	129629249

However I obtained same file as one without '-X' option, i.e. the result contained all region including above the regions. How can I fix this? 

Thank you.

**Comment by alachins** [comment]
Hi,
Everything seems correct in the remove.txt file. If you could send me
the files to reproduce this, I will check what is happening there.
Best regards,
Nikos A.

On Wed, Jun 23, 2021 at 10:43 AM ymatmt ***@***.***> wrote:
>
> Hi,
>
> I want to remove telomere regions in the genome so I run raisd using -X option with tab txt as follows,
>
> RAiSD -n vcf_run -t -f -P -R -s -A 0.995 -X remove.txt -I ${VFILE}
>
> cat remove.txt
> A1 0 100000
> A1 243404654 243504654
> X 0 100000
> X 129529249 129629249
>
> However I obtained same file as one without '-X' option, i.e. the result contained all region including above the regions. How can I fix this?
>
> Thank you.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Nikolaos Alachiotis

**Comment by ymatmt** [comment]
Hi,

Thank you for your kind comments. I confirm the chromosome number of VCF file then the chromosome character in VCF file is different from it in the remove file. So I revise the remove file then the problem is fixed! I am so sorry bothering you.

Thank you!
