### ISSUE TITLE
test data (wget 139.91.162.50/raisd_data/d1.tar.gz)

### ISSUE THREAD

**Issue by peterthorpe5** [alachins/raisd#29]
Dear RAISD,

I cannot download the test data to test the install:

    wget 139.91.162.50/raisd_data/d1.tar.gz

    --2021-11-18 10:44:57--  http://139.91.162.50/raisd_data/d1.tar.gz
    Connecting to 139.91.162.50:80...

The terminal fails to connect to that IP address...  Would it be possible to update the link on github?

regards,

Peter Thorpe

**Comment by alachins** [comment]
Hi Peter,
I have the repo here: https://github.com/pephco/RAiSD and included a test file.
Best regards,
Nikos

**Comment by peterthorpe5** [comment]
superb, this works - thank you!

Pete
