### ISSUE TITLE
Applicability of RAiSD

### ISSUE THREAD

**Issue by jckhearn** [alachins/raisd#3]
Hello Nikolaos & Pavlos,

I'd like to apply RAiSD to my own dataset but need to check how applicable it is an approach. I have two populations, each sampled before and after fixation of a trait of interest, separated by ~120-150 generations. There are also strong candidate loci for sweep location. Samples are pools of 40 individuals each. 

1. Are poolseq-derived allele frequencies, and this short time interval for a (suspected hard) sweep appropriate to analyse in RAiSD? Further to this, is it best to analyse all the data together or only the 'swept' samples?

2. Is ploidy (-y) per sample or the entire dataset?

There are alternative approaches, but RAiSD is particularly interesting to me and a naive run of the program was easy to do and completed quickly as described.

Best wishes,
Jack

**Comment by orijitghosh** [comment]
Hi,
Just wanted to know if any changes were made to accommodate poolseq data yet?

**Comment by alachins** [comment]
I am going to implement the feature to assign weights to the mu
statistic factors within the next few days. So, in principle, you will
be able to use poolseq data if you give no weight to LD.

On Mon, Jul 25, 2022 at 2:25 PM Arijit Ghosh ***@***.***> wrote:
>
> Hi,
> Just wanted to know if any changes were made to accommodate poolseq data yet?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.Message ID: ***@***.***>



-- 
Nikolaos Alachiotis

**Comment by orijitghosh** [comment]
@alachins , great! Will you let us know in this issue thread?

**Comment by alachins** [comment]
this feature is now implemented in version 3.1.
you can find it here: https://github.com/pephco/RAiSD
